### ISSUE TITLE
I pulled the Lifx plugin out, but I'd like to attribute it to someone correctly

### ISSUE THREAD

**Issue by madpilot** [nfarina/homebridge-legacy-plugins#11]
Hey,

I've pulled the Lifx code out to it's own repo: https://github.com/madpilot/homebridge-lifx but I'd like to transfer ownership of it back to whoever originally wrote it (or at least correctly attribute them).

Who was it?

Thanks!

**Comment by KraigM** [comment]
I have a script you can use to extract the original commits but only for lifx.  Just remove the .txt extension, change the dependencies in the json to be only the ones required for lifx, then run "sh extract-legacy-plugin.sh lifx platforms/LIFx.js".  It should extract all changes to that file plus changes to the package.json (ignoring dependencies not found in the json) and convert the history to look like it was an independent plugin from the start yet use the exact same commit metadata (author, date time, message, etc).  Works on Mac, but should work on Linux too.

[extract-dependencies.json.txt](https://github.com/nfarina/homebridge-legacy-plugins/files/46743/extract-dependencies.json.txt)
[extract-legacy-plugin.sh.txt](https://github.com/nfarina/homebridge-legacy-plugins/files/46744/extract-legacy-plugin.sh.txt)

**Comment by KraigM** [comment]
You can forcefully pull in my fork and strip you change.  I applied you change to history cleaned with the above script.

**Comment by KraigM** [comment]
https://github.com/KraigM/homebridge-lifx

**Comment by KraigM** [comment]
I also fixed your commit. You committed the node_modules

**Comment by madpilot** [comment]
Looks like https://github.com/nmelo/homebridge-lifx is official. Closing this.
