### ISSUE TITLE
Nest is failing to initialize

### ISSUE THREAD

**Issue by keloin** [nfarina/homebridge-legacy-plugins#2]
Loading 1 platforms...
[Nest] Initializing Nest platform...
Loading legacy platform Nest
/usr/local/lib/node_modules/homebridge-legacy-plugins/platforms/Nest.js:91
        .setCharacteristic(Characteristic.Model, device.model_version)

**Comment by billburgess** [comment]
Same here. +1

**Comment by nfarina** [comment]
Is that the complete log/stacktrace? The Nest platform initializes and runs correctly for me.

**Comment by nfarina** [comment]
OK - I'm pretty sure this was caused by #1 - could you update and try again?

Some platforms also exported an `accessory` property (unnecessarily) and the bug described by #1 meant that instead of outright failing to load the platform, it instead attempts to load the exported accessory var. Subtle!

**Comment by keloin** [comment]
It is working now after I upgraded everything to the latest versions. Was not working yesterday though. Let's close this issue.

**Comment by nfarina** [comment]
Awesome, thanks!
