### ISSUE TITLE
Wink configuration

### ISSUE THREAD

**Issue by keloin** [nfarina/homebridge-legacy-plugins#4]
OK, now when all them initial problems are solved ... 
How do I configure wink? 
Where do I get client ID and etc? 

Thanks!

**Comment by nfarina** [comment]
Past contributors to Wink: @maddox @KraigM @nfarina @masonjames @alistairg

Anyone want to volunteer to be maintainer of the Wink platform and spin off a new plugin for it?

**Comment by maddox** [comment]
I don't personally use Wink anymore, so I wouldn't be able to actually make sure it works :/

**Comment by alistairg** [comment]
I also dumped Wink…. so nothing to test against :(

**Comment by KraigM** [comment]
I still have wink but I only use it for a couple zigbee devices that needed a hub to connect to.  If no one else will take it I will, at least until someone else comes along.

**Comment by nfarina** [comment]
@KraigM I think you're the only one who can do it :) I don't have Wink personally and @masonjames was on the contributor list for unrelated `require` fix.

**Comment by KraigM** [comment]
Alright, I will work on separating that out into a new plugin repo.  I can take LogitechHarmony as well.

**Comment by nfarina** [comment]
:+1: :smile:

**Comment by KraigM** [comment]
@keloin You configure it as follows:

{
    "platform": "Wink",
    "name": "Wink",
    "client_id": "YOUR_WINK_API_CLIENT_ID",
    "client_secret": "YOUR_WINK_API_CLIENT_SECRET",
    "username": "your@email.com",
    "password": "WINK_PASSWORD"
}

The client_id and client_secret are application API keys.  We can look at getting one for home bridge but as it stands, you have to email wink and ask them for one.  Usually takes about a day or two.  

The username and password are what you setup your account with when you setup wink.

After that all the wink devices will just show up.  Right now it only has support for light bulbs and locks.  The light bulb code was written by the other contributors and I wrote the door lock code.  Can't guarantee the light bulb code is working, but lock definitely does.  What devices do you have on your wink?

**Comment by keloin** [comment]
Hi @KraigM,

I was thinking about controlling my security cam (Canary) that can be integrated with Wink. Like arm/disarm, etc.
Plus I am hoping my door lock (when they arrive) will also get integrated into Wink.

Do I simply email QUESTIONS@WINK.COM to get the client ID?

Thanks!

**Comment by pdlove** [comment]
In a few more months I can take over the Wink plugin when I have a bit of time free from work to learn node.js a bit better. I want to add power plugs, garage doors and smoke alarms to it. Does anyone know if any of the phone apps actually use smoke alarm information?

For those that moved away from Wink, what did you move to?

@keloin Yes. It took them 3 days to get me my code to me.

**Comment by masonjames** [comment]
Hiya everyone,

To confirm, I also do not have a wink device. Just philips hue, wemo, and lockitron.  Will look into other ways I can help.  Thanks!

**Comment by KraigM** [comment]
@nfarina You can close this issue.  @keloin if you are still having issues, you can jump on the #slack channel #homebridge-wink or write up a new issue on the new repo https://github.com/KraigM/homebridge-wink
