### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by raspberry007** [nfarina/homebridge-legacy-plugins#6]
Hello,

I tried to issue "sudo npm install -g homebridge-legacy-plugins --verbose"
However, it breaks at "serialport" installation. I can npm serial port locally, if I issue "sudo npm install -g serialport", the installation breaks. Without sudo it won't install globally. 

I am on RPi2.

node -v:
0.12.6 

gcc -v:4.8.2

uname -a:
Linux raspberrypi2 4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7  l GNU/Linux

npm ERR! Linux 4.1.7-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-legacy-plugins" "--verbose"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! serialport@2.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@2.0.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

**Comment by nfarina** [comment]
This dependency has been removed (we'd had this same issue before). If @Cosmo would like to move `GenericRS232Device.js` into its own plugin I think that would be the best solution! In the meantime it's out of legacy deps.

**Comment by Cosmo** [comment]
@alex1sh @nfarina It's on my todo list, thanks for reminding :)
