### ISSUE TITLE
not able to get install going on homebridge

### ISSUE THREAD

**Issue by Slepperpon** [nfarina/homebridge-legacy-plugins#8]
i@raspberrypi ~/homebridge $ npm run start
npm ERR! Linux 4.1.7-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/homebridge/npm-debug.log
pi@raspberrypi ~/homebridge $ cd
pi@raspberrypi ~ $ ls -l
total 10804
drwxr-xr-x 2 pi pi     4096 Sep 24 15:33 Desktop
drwxr-xr-x 5 pi pi     4096 Jan  1  1970 Documents
drwxr-xr-x 2 pi pi     4096 Nov 11 16:02 Downloads
drwxr-xr-x 7 pi pi     4096 Nov 11 17:09 homebridge
drwxr-xr-x 2 pi pi     4096 Sep 24 15:33 Music
drwxr-xr-x 6 pi pi     4096 Oct 13 17:19 node-v4.2.1-linux-armv7l
-rw-r--r-- 1 pi pi 11003942 Oct 13 17:19 node-v4.2.1-linux-armv7l.tar.gz
-rw-r--r-- 1 pi pi    11637 Nov 11 15:58 npm-debug.log
drwxr-xr-x 2 pi pi     4096 Sep 24 15:33 Pictures
drwxr-xr-x 2 pi pi     4096 Sep 24 15:33 Public
drwxrwxr-x 2 pi pi     4096 Jan  1  1970 python_games
drwxr-xr-x 2 pi pi     4096 Sep 24 15:33 Templates
drwxr-xr-x 2 pi pi     4096 Sep 24 15:33 Videos
pi@raspberrypi ~ $ 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:142:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:58:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at handleExists (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:318:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete](fs.js:212:19)
5 verbose cwd /home/pi/homebridge
6 error Linux 4.1.7-v7+
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
8 error node v4.2.1
9 error npm  v2.14.7
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     https://github.com/npm/npm/issues
12 verbose exit [ 1, true ]

**Comment by nfarina** [comment]
The latest version of homebridge is installed through npm (`npm install -g homebridge`) and to start it up you use the provided `homebridge` binary. Take a look at the homebridge README for more info.

**Comment by Slepperpon** [comment]
pi@raspberrypi ~ $ homebridge
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
Loaded plugin: homebridge-legacy-plugins
Registering accessory 'homebridge-legacy-plugins.AD2USB'
Registering accessory 'homebridge-legacy-plugins.Carwings'
Registering accessory 'homebridge-legacy-plugins.ELKM1'
Registering accessory 'homebridge-legacy-plugins.FileSensor'
Registering accessory 'homebridge-legacy-plugins.GenericRS232Device'
Registering accessory 'homebridge-legacy-plugins.HomeMatic'
Registering accessory 'homebridge-legacy-plugins.HomeMaticThermo'
Registering accessory 'homebridge-legacy-plugins.HomeMaticWindow'
Registering accessory 'homebridge-legacy-plugins.HttpGarageDoorOpener'
Registering accessory 'homebridge-legacy-plugins.HttpHygrometer'
Registering accessory 'homebridge-legacy-plugins.HttpThermometer'
Registering accessory 'homebridge-legacy-plugins.Hyperion'
Registering accessory 'homebridge-legacy-plugins.LiftMaster'
Registering accessory 'homebridge-legacy-plugins.Lockitron'
Registering accessory 'homebridge-legacy-plugins.Tesla'
Registering accessory 'homebridge-legacy-plugins.WeMo'
Registering accessory 'homebridge-legacy-plugins.X10'
Registering accessory 'homebridge-legacy-plugins.iControl'
Registering accessory 'homebridge-legacy-plugins.mpdclient'
Registering platform 'homebridge-legacy-plugins.Domoticz'
Registering platform 'homebridge-legacy-plugins.HomeAssistant'
Registering platform 'homebridge-legacy-plugins.HomeSeer'
Registering platform 'homebridge-legacy-plugins.ISY'
Registering platform 'homebridge-legacy-plugins.LIFx'
Registering platform 'homebridge-legacy-plugins.LogitechHarmony'
Registering platform 'homebridge-legacy-plugins.MiLight'
Registering platform 'homebridge-legacy-plugins.Openhab'
Registering platform 'homebridge-legacy-plugins.SmartThings'
Registering platform 'homebridge-legacy-plugins.Telldus'
Registering platform 'homebridge-legacy-plugins.TelldusLive'
Registering platform 'homebridge-legacy-plugins.Wink'
Registering platform 'homebridge-legacy-plugins.YamahaAVR'

## Registering platform 'homebridge-legacy-plugins.ZWayServer'

Couldn't find a config.json file at '/home/pi/.homebridge/config.json'. Look at config-sample.json for examples of how to format your config.js and add your home accessories.
 I don't have a homebridge under pi directory

**Comment by nfarina** [comment]
You need to create the directory if it doesn't exist.

**Comment by Slepperpon** [comment]
i made a directroy for homebridge then get error could not find config.jason in home/pi/.homebridge that directory is empty

Date: Wed, 11 Nov 2015 10:04:38 -0800

**Comment by Slepperpon** [comment]
I deleted empty homebridge dir and cloned homebridge and installed now i have all files in homebridge folder by when i run homebridge it says 
Couldn't find a config.json file at '/home/pi/.homebridge/config.json'. Look at config-sample.json for examples of how to format your config.js and add your home accessories.  
to me it is looking in .homebridge  and the dir i have is homebridge
Date: Wed, 11 Nov 2015 09:52:26 -0800

**Comment by Slepperpon** [comment]
Sorry for the questions i think i have it i was just looking for the old setup way and there was no folder under pi.I now have it running but it finds harmony activities then initializing them then just keeps repeating harmony hub refresh status

Date: Wed, 11 Nov 2015 10:04:38 -0800
